CREATE LOGIN [GenesysTT]
    WITH PASSWORD = N't@w|lcytrkgwvhcpiA`l=wp%msFT7_&#$!~<YsleyosyfpyL' MUST_CHANGE, SID = 0xE6A5CA1DE6D87F4B92B534CEDC8E8EB6, DEFAULT_DATABASE = [GenesysProject], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

