//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTennis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.SlotsAllocs = new HashSet<SlotsAlloc>();
        }
    
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> IsOrganiser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string EmpPass { get; set; }
        public string OTP { get; set; }
        public Nullable<System.DateTime> OTPGeneratedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlotsAlloc> SlotsAllocs { get; set; }
    }
}
