//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTennis
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryRecord
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmailID { get; set; }
        public System.DateTime IsOrganiser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int SlotID { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public int SlotAllocID { get; set; }
        public string Status { get; set; }
        public int TableID { get; set; }
        public System.DateTime SlotCreatedDate { get; set; }
        public Nullable<System.DateTime> SlotUpdatedDate { get; set; }
    }
}
