//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTennis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotChart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlotChart()
        {
            this.SlotsAllocs = new HashSet<SlotsAlloc>();
            this.SlotStatus = new HashSet<SlotStatu>();
        }
    
        public int SlotID { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlotsAlloc> SlotsAllocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlotStatu> SlotStatus { get; set; }
    }
}
