//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTennis
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TennisTable
    {
        public int TableID { get; set; }
        public string TableArena { get; set; }
    }
}
